credentials:
  usernames:
    carlos:
      email: carlos@example.com
      name: Carlos Rodríguez
      password: '$2b$12$4g/GhviWBuLCrJecxXiTYOqq6gaK8bErKQdJbYKmmR6BZawn9q4H.'  # demo1234

cookie:
  expiry_days: 1
  key: abcdef
  name: encuesta_cookie
