credentials:
  usernames:
    carlos:
      email: carlos@example.com
      name: Carlos Rodríguez
      password: '$2b$12$DWUv6Y0DGljFKdmE/cvGhu68EKaPKUOkoWfHArbDoN3YiQctv0U.O' 

cookie:
  expiry_days: 1
  key: abcdef
  name: encuesta_cookie
