credentials:
  usernames:
    carlos:
      email: carlos@example.com
      name: Carlos Rodríguez
      password: '$2b$12$XuWmApL3S3yZ3xiT9rX3Au0DFzOv29lQlRuGqraOK81w5JAVPvU9y'

cookie:
  expiry_days: 1
  key: abcdef
  name: encuesta_cookie
